version: "3.7"

services:
  mysql-notificationservice:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'notification_db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-notificationservice-data:/var/lib/mysql

volumes:
    mysql-notificationservice-data:

