version: "3.7"

services:
  mysql-departmentservice:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'department_db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - mysql-departmentservice-data:/var/lib/mysql

volumes:
    mysql-departmentservice-data:

